#!/usr/bin/env python3
"""
Build nightwatch.html — the evidence behind the star counts on the forecast page.

    python3 make_nightwatch.py

The forecast page states a number: how many stars are visible in the region of sky where
the Milky Way core sits. A number nobody can check is worth very little, so this page shows
the stacked frames it came from, with the target regions ringed and every detection marked.

Regenerated by publish.sh. Reads nightwatch_log.json and the frames in nightwatch/.
"""

import json
import os
import re
import sys
from datetime import datetime, timedelta, timezone

LOG = "nightwatch_log.json"
OUT = "nightwatch.html"
EDT = timezone(timedelta(hours=-4))


def load():
    try:
        return json.load(open(LOG))
    except Exception:
        return []


def main():
    log = load()
    if not log:
        open(OUT, "w").write("<!doctype html><meta charset=utf-8>"
                             "<title>Night watch</title><p>No captures yet.</p>")
        print(f"wrote {OUT} (empty)")
        return 0

    rows = log[-48:]
    latest = rows[-1]
    lt = datetime.fromisoformat(latest["time"])

    def tg(e, k):
        return (e.get("targets") or {}).get(k) or {}

    fl = [max(0.0, tg(e, "core").get("flux", 0) or 0) for e in rows]
    mx = max(fl + [1])

    strip = "".join(
        f'<a class="nb {"good" if f/mx > .5 else "warn" if f/mx > .15 else "bad"}" '
        f'href="#c{i}" style="--f:{f/mx:.2f}" '
        f'title="{datetime.fromisoformat(e["time"]):%a %H:%M} — '
        f'{tg(e, "core").get("stars", "-")} stars, flux {f:.0f}"><i></i>'
        f'<span>{datetime.fromisoformat(e["time"]):%H:%M}</span></a>'
        for i, (e, f) in enumerate(zip(rows, fl)))

    cards = []
    for i, e in enumerate(rows[::-1]):
        t = datetime.fromisoformat(e["time"])
        core, rho, tea = tg(e, "core"), tg(e, "rho"), tg(e, "teapot")
        shot = e.get("shot")
        img = (f'<img loading="lazy" src="{shot}" alt="stacked frame {t:%H:%M}">'
               if shot and os.path.exists(shot) else
               '<div class="noimg">frame not kept</div>')
        cards.append(
            f'<figure class="cap" id="c{len(rows)-1-i}">{img}'
            f'<figcaption><b>{t:%a %d %b · %H:%M}</b><br>'
            f'<span class="tt">core</span> {core.get("stars","-")} stars · '
            f'flux {core.get("flux",0):,.0f} · peak {core.get("peak",0):.0f}× · '
            f'alt {core.get("alt","—")}°<br>'
            f'<span class="tt rho">rho</span> {rho.get("stars","-")} stars · '
            f'flux {rho.get("flux",0):,.0f} · peak {rho.get("peak",0):.0f}×<br>'
            f'<span class="tt tea">teapot</span> {tea.get("stars","-")} stars · '
            f'flux {tea.get("flux",0):,.0f}<br>'
            f'<span class="dim">{e.get("n_stacked","?")} of {e.get("n_frames","?")} frames '
            f'stacked · noise σ {e.get("sigma","—")} · '
            f'{len(e.get("sources",[]))} sources in sky</span>'
            f'</figcaption></figure>')

    tbl = "".join(
        f'<tr><td>{datetime.fromisoformat(e["time"]):%H:%M}</td>'
        f'<td class="n">{tg(e,"core").get("stars","-")}</td>'
        f'<td class="n">{tg(e,"core").get("flux",0):,.0f}</td>'
        f'<td class="n">{tg(e,"rho").get("stars","-")}</td>'
        f'<td class="n">{tg(e,"rho").get("flux",0):,.0f}</td>'
        f'<td class="n">{tg(e,"core").get("alt","—")}°</td>'
        f'<td class="n">{e.get("sigma","—")}</td>'
        f'<td class="n">{e.get("sky_lum","—")}</td></tr>'
        for e in rows[::-1])

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Night watch — can the core be seen?</title>
<meta name="color-scheme" content="dark light">
<style>
:root{{--ground:#0A0D14;--surface:#121722;--ink:#E7ECF5;--body:#BAC4D4;--muted:#7A8698;
--rule:#232B39;--accent:#E3A445;--good:#6FBF95;--warn:#E3A445;--bad:#E8705C;
--sans:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
--mono:ui-monospace,"SF Mono",SFMono-Regular,Menlo,Consolas,monospace;
--serif:ui-serif,"Iowan Old Style",Palatino,Georgia,serif}}
*{{box-sizing:border-box}}
body{{margin:0;background:var(--ground);color:var(--body);font-family:var(--sans);
line-height:1.6;padding-bottom:3rem}}
.wrap{{max-width:58rem;margin:0 auto;padding:0 clamp(1rem,3.5vw,1.6rem)}}
.bar{{position:sticky;top:0;z-index:9;background:var(--ground);border-bottom:1px solid var(--rule)}}
.bar-in{{max-width:58rem;margin:0 auto;padding:.5rem clamp(1rem,3.5vw,1.6rem)}}
.bar a{{font-family:var(--mono);font-size:.7rem;letter-spacing:.1em;text-transform:uppercase;
color:var(--muted);text-decoration:none}}
.bar a:hover{{color:var(--accent)}}
h1{{font-family:var(--serif);color:var(--ink);font-size:clamp(1.4rem,5vw,2rem);margin:1.6rem 0 .3rem}}
h2{{font-family:var(--serif);color:var(--ink);font-size:1.15rem;margin:2.2rem 0 .7rem}}
p{{max-width:44rem}}
.card{{background:var(--surface);border:1px solid var(--rule);border-radius:4px;padding:1.1rem}}
.big{{font-family:var(--mono);font-size:clamp(2.4rem,10vw,3.4rem);line-height:1;
font-variant-numeric:tabular-nums}}
.big span{{font-size:.85rem;color:var(--muted);margin-left:.5rem}}
.good{{color:var(--good)}}.warn{{color:var(--warn)}}.bad{{color:var(--bad)}}
.dim{{color:var(--muted)}}
.strip{{display:flex;gap:2px;align-items:flex-end;height:76px;margin:1.1rem 0 .3rem;overflow-x:auto}}
.nb{{flex:1 0 20px;min-width:20px;display:flex;flex-direction:column;justify-content:flex-end;
height:100%;text-decoration:none}}
.nb i{{display:block;width:100%;height:calc(6px + var(--f,0)*50px);border-radius:2px;background:var(--rule)}}
.nb.good i{{background:var(--good)}}.nb.warn i{{background:var(--warn)}}.nb.bad i{{background:var(--bad)}}
.nb span{{font-family:var(--mono);font-size:.5rem;color:var(--muted);text-align:center;margin-top:.2rem}}
.caps{{display:grid;gap:1rem;grid-template-columns:1fr;margin-top:1rem}}
@media(min-width:44rem){{.caps{{grid-template-columns:1fr 1fr}}}}
.cap{{margin:0;background:var(--surface);border:1px solid var(--rule);border-radius:4px;
overflow:hidden}}
.cap img{{display:block;width:100%}}
.noimg{{height:180px;display:flex;align-items:center;justify-content:center;color:var(--muted);
font-family:var(--mono);font-size:.75rem}}
figcaption{{padding:.6rem .8rem;font-family:var(--mono);font-size:.7rem;line-height:1.7}}
.tt{{display:inline-block;min-width:3.6rem;color:#7dd3fc}}
.tt.rho{{color:#ffd166}}.tt.tea{{color:#9fb3c8}}
table{{border-collapse:collapse;width:100%;font-size:.82rem;font-family:var(--mono)}}
th,td{{text-align:left;padding:.35rem .6rem;border-bottom:1px solid var(--rule);white-space:nowrap}}
th{{font-size:.6rem;letter-spacing:.1em;text-transform:uppercase;color:var(--muted)}}
td.n{{text-align:right;font-variant-numeric:tabular-nums}}
.scroll{{overflow-x:auto}}
.note{{color:var(--muted);font-size:.86rem}}
.legend span{{display:inline-block;margin-right:1rem;font-family:var(--mono);font-size:.72rem}}
</style>
</head>
<body>
<div class="bar"><div class="bar-in"><a href="forecast.html">← Forecast</a></div></div>
<div class="wrap">
<h1>Can the core actually be seen?</h1>
<p>The webcam at Lopstick was plate-solved from its own stars: <b>bearing 178.5°</b>,
94° wide, pitched 3° below level. Every target of this trip falls inside that frame —
the Milky Way core, Rho Ophiuchi, M8 and M20 — at the same low southern altitudes you
will be shooting them at, from 16.6 km away.</p>
<p>So this is not a cloud proxy. A star either shows through or it does not. It also covers
the case the satellite handles worst: infrared struggles with low cloud whose tops sit near
ground temperature, and low cloud is exactly what blocks a target at 16°.</p>

<div class="card">
  <div class="big {'good' if (tg(latest,'core').get('stars') or 0) >= 3 else 'warn' if (tg(latest,'core').get('stars') or 0) >= 1 else 'bad'}">
    {tg(latest,'core').get('stars','—')}<span>stars in the core region · {lt:%a %H:%M}</span></div>
  <p class="note">Flux {tg(latest,'core').get('flux',0):,.0f} · brightest source
  {tg(latest,'core').get('peak',0):.0f}× the noise · core at
  {tg(latest,'core').get('alt','—')}° altitude</p>
  <div class="strip">{strip}</div>
  <p class="note">One bar per capture, height is light collected in the core region.
  Click a bar to jump to that frame.</p>
</div>

<h2>Why flux and not just a count</h2>
<p>A star count depends on where the detection threshold lands, and the stack noise moves
between captures. Two grabs two minutes apart gave 15 sources and then 5 — not because the
sky changed, but because σ went from 0.78 to 0.88 and the 6σ cut moved with it. Flux is the
total light collected and does not care where a threshold sits, so it is the number to
compare across captures and across nights.</p>
<p class="legend"><span style="color:#7dd3fc">● core region</span>
<span style="color:#ffd166">● Rho Ophiuchi</span>
<span style="color:#9fb3c8">● teapot</span>
<span style="color:#3ddc84">● detected source</span></p>

<h2>The frames</h2>
<p>Each is a median stack of the 30 least-compressed frames from a 30-second grab at 1080p,
stretched so faint stars are visible, masked to sky only. Newest first.</p>
<div class="caps">{"".join(cards)}</div>

<h2>Every reading</h2>
<div class="scroll"><table>
<thead><tr><th>time</th><th>core ★</th><th>core flux</th><th>rho ★</th><th>rho flux</th>
<th>core alt</th><th>σ</th><th>sky</th></tr></thead>
<tbody>{tbl}</tbody></table></div>
<p class="note" style="margin-top:1rem">Captured every 15 minutes through the dark hours.
Calibrated on the night of 4 Aug 2026 — the only fully dark night before the trip.</p>
</div>
</body>
</html>"""
    open(OUT, "w").write(html)
    print(f"wrote {OUT} — {len(rows)} captures, "
          f"{sum(1 for e in rows if e.get('shot') and os.path.exists(e['shot']))} frames")
    return 0


if __name__ == "__main__":
    sys.exit(main())
